### ISSUE TITLE
ESOCC Vienna Austria Logo - find better quality

### ISSUE THREAD

**Issue by marigianna-iaas** [uniba-dsg/peace-ws#3]

**Comment by koppor** [comment]
Playing around with the image url http://i1.wp.com/esocc2016.eu/wp-content/uploads/2016/03/cropped-esocc_logo-3.png lead to http://i1.wp.com/esocc2016.eu/wp-content/uploads/2016/03/cropped-esocc_logo-2.png. Note that the `3` has been replaced with a `2`. I will try.

**Comment by koppor** [comment]
Please check again. I exchanged the logo URL in 8a7130f
